export const ERROR_CODES = {
    // 400
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',

    // 401
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',

    // 403
    FORBIDDEN: 'FORBIDDEN',

    // 404
    NOT_FOUND: 'NOT_FOUND',

    // 405
    METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',

    // 409
    CONFLICT: 'CONFLICT',

    // 500
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
